### PR TITLE
feat: add `get_child_by_name` method

### PR DESCRIPTION
**Pull request by chainyo**
Hi thanks for the project, it's super easy to use and fast as expected. From the benchmarks on my xml files it takes on average less than 2 seconds (~1.9) to load while the python `xml` package takes almost 5 seconds (~4.8) on xml files with 30.000 items. This is lit 🔥 

I'm looking for a feature that could allow to select Node children based on their name to allow easy manipulation for heavy nested nodes. So I added it to the `Node` struct. Let me know if it needs more tests. It could be also good to add some python tests. I recently tested `rye` for rust/python modules using maturin and it's super nice for project maintainer, wdyt?

### CODE REVIEW

**Comment by nephi-dev** [comment]
Hey, thanks for the PR, there's an local branch with this functionality already implemented, I will push it today, and merge with your PR

**Comment by nephi-dev** [comment]
The python tests may require some time but I will surely add them to the backlog

**Comment by chainyo** [comment]
> The python tests may require some time but I will surely add them to the backlog

Good, I can help for sure.

> Hey, thanks for the PR, there's an local branch with this functionality already implemented, I will push it today, and merge with your PR

Should I close my PR then?

**Comment by nephi-dev** [comment]
Yep, closing the PR, if the new code is not enough for your usages fell free to open a new pr please

**Pull request closed without merging**
